### ISSUE TITLE
Alternative solution for Android?

### ISSUE THREAD

**Issue by gimmeAll** [Ayzzzzzzzzzzz/RemoveDiscover#2]
Seeing as the provided application works on iPhones only, is there a way to use NextDNS (or another filtering program of some sort) on Android to block certain hosts of Snapchat in order to block the discovery page without the risk of getting banned? If so, what would those hosts be?

**Comment by x-x6n** [comment]
Issue is with NextDNS, your friends' snaps and Spotlight are on the same server. So even if you blocked the correct subdomains, you wouldn't be able to view any snaps.

**Comment by Ayzzzzzzzzzzz** [comment]
exactly. But also snapchat is going strictly agains modifying app data. Its going to be hard in the future, also on android
